version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 30
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    commit-message:
      prefix: "actions"
    open-pull-requests-limit: 30