openapi: 3.0.0
info:
  title: Produksjonsplassregisteret
  description: API for å kunne hente ut informasjon om produksjonsplasser og relatert informasjon.
  version: 0.1.0
servers:
  - url: http://localhost:8080
    description: For å teste lokalt på maskinen din

security:
  - BasicAuth: [ ]

paths:

  /produksjonsplasser/getProduksjonsplassByProduksjonsplassId/{produksjonsplassid}:
    get:
      summary: Returnerer informasjon om produksjonsplass hvis den eksisterer.
      description: Produksjonsplass som matcher ProduksjonsplassIDen
      operationId: getProduksjonsplassByProduksjonsplassId
      parameters:
        - in: path
          name: produksjonsplassid
          schema:
            type: string
          required: true
          description: ID til produksjonsplass
      tags:
        - Produksjonsplasser
      responses:
        '200': # status code
          description: En produksjonsplass
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produksjonsplass'
        '404':
          description: Finner ikke produksjonsplassen med denne id-en
        '500':
          $ref: '#/components/responses/500Error'
          description: Uforventet feil

  /produksjonsplasser/getAllProduksjonsplasser:
    get:
      summary: Returnerer alle aktive produksjonsplasser i registeret UTEN kontaktinformasjon
      description: Produksjonsplass som matcher ProduksjonsplassIDen
      operationId: getAllProduksjonsplasser
      tags:
        - Produksjonsplasser
      responses:
        '200': # status code
          description: Liste over alle aktive produksjonsplasser
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produksjonsplass'
        '404':
          description: Klarer ikke returnere noen produksjonsplasser
        '500':
          $ref: '#/components/responses/500Error'
          description: Uforventet feil

  /produksjonsplasser/getProduksjonsplassByMatsKildeRefId/{kildeRefId}:
    get:
      summary: Returnerer informasjon om produksjonsplass hvis den eksisterer.
      description: Produksjonsplass som matcher kildeRefId
      operationId: getProduksjonsplassByMatsKildeRefId
      parameters:
        - in: path
          name: kildeRefId
          schema:
            type: string
          required: true
          description: ID til kildeRefId for produksjonsplass
      tags:
        - Produksjonsplasser
      responses:
        '200': # status code
          description: En produksjonsplass
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Produksjonsplass'
        '404':
          description: Finner ikke produksjonsplassen med denne id-en
        '500':
          $ref: '#/components/responses/500Error'


  /produksjonsplasser/{produksjonsplassid}/sone/{radius}:
    get:
      summary: Returnerer en liste over produksjonsplasser innenfor angitt radius til en produksjonsplass som er episenter.
      description: Liste over alle produksjonsplasser som finnes innenfor en gitt radius. Listen kan være tom.
      operationId: getProduksjonsplasserISoneByProduksjonsplassId
      parameters:
        - in: path
          name: produksjonsplassid
          schema:
            type: string
          required: true
          description: Id til produksjonsplass som er episenter/senterpunkt for sonen
        - in: path
          name: radius
          schema:
            type: integer
          required: true
          description: Radius i meter rundt episenter
      tags:
        - Produksjonsplasser
      responses:
        '200': # status code
          description: En liste over produksjonsplasser
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produksjonsplass'
        '500':
          $ref: '#/components/responses/500Error'

  /produksjonsplasser/getProduksjonsplasserISoneFraKoordinat:
    get:
      summary: Returnerer en liste over produksjonsplasser innenfor en angitt sone. Sonen blir generert av oppgitte GPS-koordinater og en radius.
      description: Liste over alle produksjonsplasser som finnes innenfor en gitt radius fra et GPS punkt.
      operationId: getProduksjonsplasserISoneByCoordinates
      parameters:
        - in: query
          name: radius
          schema:
            type: integer
            default: 3000
          required: false
          description: Radius (i meter) som beskriver størrelsen for sone rundt episenteret. Default er 3 km.
        - in: query
          name: lengdegrad
          schema:
            type: float
          required: true
          description: Lengdegrad (longitude) for punktet som er senterpunkt av sonen.
        - in: query
          name: breddegrad
          schema:
            type: float
          required: true
          description: Breddegrad (latitude) for punktet som er senterpunkt av sonen.
      tags:
        - Produksjonsplasser
      responses:
        '200': # status code
          description: En liste med produksjonsplasser som er innenfor sonen. Listen kan være tom.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produksjonsplass'

        '500':
          $ref: '#/components/responses/500Error'

  /kontakt-info:
    get:
      summary: Returnerer kontaktinformasjon for for en liste med tilsynsobjektider
      description: Returnerer driftsansvarlige med kontaktinformasjon for et tilsynsobjekt
      operationId: getKontaktInfo
      parameters:
        - in: query
          name: tilsynsobjektIdList
          schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: En liste med driftsansvarlige med kontaktinfo. Listen kan være tom
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Driftsansvarlig"
        '500':
          $ref: '#/components/responses/500Error'


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Produksjonsplass:
      type: object
      properties:
        produksjonsplassid:
          type: integer
          format: int64
          example: 12343212343
        lokasjoner:
          type: array
          items:
            $ref: "#/components/schemas/Lokasjon"
          description: Liste over lokasjoner knyttet mot produksjonsplassen
        kategori:
          type: string
          example: Hobbyfjørfehold
          description: Kategori beskriver aktiviteten på en produksjonsplass.
        arter:
          type: array
          items:
            $ref: "#/components/schemas/Art"
          description: Liste over arter som holdes på lokasjonen
        adresse:
          $ref: "#/components/schemas/Adresse"
        driftsansvarlig:
          $ref: "#/components/schemas/Driftsansvarlig"

    Art:
      type: object
      properties:
        artstype:
          type: string
          enum: [HONS, AND, GJESS]
          example: HONS
          description: Kodeverk for hvilke arter som er tilatt.
        antall:
          type: integer
          example: 23

    Driftsansvarlig:
      type: object
      properties:
        fornavn:
          type: string
          example: Jens
        etternavn:
          type: string
          example: Pikenes
        adresse:
          $ref: '#/components/schemas/Adresse'
        telefonnummer:
          type: string
          example: 123456789
        organisasjonsnummer:
          type: string
          example: 987654321
        foedselsnummer:
          type: string
          example: 01037922334
    Adresse:
      type: object
      properties:
        adressenavn:
          type: string
          example: Holsetgata 55
        poststed:
          type: string
          example: Hamar
        postnummer:
          type: string
          example: 2318

    Lokasjon:
      type: object
      properties:
        kildeRef:
          type: string
          example: 124
          description: En referanse til akkurat denne lokasjonen i kildesystemet
        geom:
          type: string
          example: POINT(-71.064543 42.28787)
          description: Koordinater som beskriver et polygon som beskriver lokasjonen

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    500Error:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string