openapi: 3.0.0
info:
  title: Hendelsesmottak for Produksjonsplassregister
  description: API for å kunne sende endringer av produksjonsplasser inn i produksjonsplassregisteret.
  version: 0.0.2
servers:
  - url: "{server}"
    description: For å teste lokalt på maskinen din

security:
  - BasicAuth: [ ]

paths:
  /produksjonsplassEndring:
    post:
      summary: Endepunkt for å ta imot endringer på en produksjonsplass
      description: Mottar endringer på en produksjonsplass og oppretter eller oppdaterer en produksjonsplass
      requestBody:
        description: Endring på en produksjonsplass
        required: true
        content:
          application/json:
            schema:
              $ref: ./Produksjonsplass/Produksjonsplass.yaml
      responses:
        '201':
          description: Created new produksjonsplass
          content:
            text/plain:
              schema:
                type: string
                example: 12345
        '204':
          description: Updated produksjonsplass successfully
          content:
            text/plain:
              schema:
                type: string
                example: 12345


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    500Error:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string