openapi: 3.0.0
x-stoplight:
  id: 5rsqq5op2wjt7
info:
  title: Produksjonsplass og Ansvar
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: local
  - url: 'https://stoplight.io/mocks/mattilsynet/produksjonsdyr/382663'
    description: mock
paths:
  '/produksjonsdyr/produksjonsplass/{id}':
    get:
      summary: produksjonsplass
      tags:
        - Produksjonsplass
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: ./models/Produksjonsplass/Produksjonsplass.yaml
        '404':
          description: Not Found
      operationId: get-produksjonsplass
      x-internal: false
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  '/ansvar/driftsansvarlig/{id}':
    get:
      summary: GetDriftsansvarlig
      tags:
        - Driftsansvarlig
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: ./models/Ansvar/Driftsansvarlig.yaml
        '404':
          description: Not Found
      operationId: get-produksjonsplass-driftsansvarlig
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  /produksjonsdyr/produksjonsplass:
    post:
      summary: PostProduksjonsplass
      tags:
        - Produksjonsplass
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: The user ID
        '400':
          description: Bad Request
      operationId: post-produksjonsdyr-produksjonsplass
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: ./models/Produksjonsplass/Produksjonsplass.yaml
        description: ''
      description: Endepunkt for å opprette en produksjonsplass
  /ansvar/driftsansvarlig:
    post:
      summary: PostDriftsansvarlig
      operationId: post-produksjonsdyr-driftsansvarlig
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: The user ID
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: ./models/Ansvar/Driftsansvarlig.yaml

