openapi: 3.0.0
x-stoplight:
  id: 5rsqq5op2wjt7
info:
  title: produksjonsdyr
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: local
  - url: 'https://stoplight.io/mocks/mattilsynet/produksjonsdyr-api/382663'
    description: mock
paths:
  '/paabegyntskjema/{id}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
        description: identen til påbegynt skjema som skal hentes opp
    get:
      summary: Henter påbegynt skjema
      tags:
        - Paabegyntskjema
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaabegyntSkjema'
              examples:
                fjorfehold1:
                  value:
                    id: 1
                    skjemanavn: fjorfehold
                    endretdato: 30.05.2023 13.12
                    datajson: '{"dyrehold":[{"id":1,"produksjonsform":"rugeegg"}]}'
        '404':
          description: Not Found
      operationId: get-paabegyntskjema-id
      description: Henter ut spesifikt påbegynt skjema som har angitt id
  /paabegyntskjema:
    get:
      summary: Henter ut alle påbegynte skjema
      tags:
        - Paabegyntskjema
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaabegyntSkjemaLite'
                  x-stoplight:
                    id: 0t5183uosro9f
              examples:
                ReturnererAntall2:
                  value:
                    - id: 1
                      skjemanavn: fjørfehold
                      endretdato: '30.05.2023 10:22'
                    - id: 2
                      skjemanavn: storfehold
                      endretdato: '29.04.2023 11:22'
        '404':
          description: Not Found
      operationId: get-paabegyntskjema
      description: Henter alle påbegynte skjema
    post:
      summary: Lagrer nytt påbegynt skjema
      tags:
        - Paabegyntskjema
      operationId: post-paabegyntskjema
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaabegyntSkjemaLite'
              examples:
                fjorfehold2:
                  value:
                    id: 2
                    skjemanavn: fjørfehold2
                    endretdato: '31.05.2023 10:22'
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaabegyntSkjema'
            examples:
              NyttSkjema:
                value:
                  skjemanavn: fjorfehold2
                  datajson: '{"dyrehold": [ {"produksjonsform": "slaktekylling" }]  }'
              Example 1:
                value:
                  skjemanavn: string
                  endretdato: string
                  datajson: string
      description: 'Lagrer skjemaet med alle opplysninger som sendes inn. '
  '/paabegyntskjema/byeier/{eierid}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        description: ident som sier hvem brukeren er
        required: true
    get:
      summary: Henter alle skjema til angitt eier
      tags:
        - Paabegyntskjema
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaabegyntSkjemaLite'
              examples:
                Example 1:
                  value:
                    - id: 1
                      skjemanavn: fjørfehold
                      endretdato: '30.05.2023 10:22'
                    - id: 2
                      skjemanavn: fjørfehold2
                      endretdato: '01.06.2023 10:22'
        '404':
          description: Not Found
      operationId: get-paabegyntskjema-byeier-eierid
      description: 'Henter ut en liste med skjema som er påbegynt av denne eieren (eierid). '
  '/produksjonsdyr/produksjonsplass/{id}':
    get:
      summary: produksjonsplass
      tags:
        - Produksjonsplass
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: ./models/Produksjonsplass/Produksjonsplass.yaml
            application/xml:
              schema:
                type: object
                properties: {}
        '404':
          description: Not Found
      operationId: get-produksjonsplass
      x-internal: false
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  /produksjonsdyr/produksjonsplass:
    post:
      summary: PostProduksjonsplass
      tags:
        - Produksjonsplass
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: The user ID
        '400':
          description: Bad Request
      operationId: post-produksjonsdyr-produksjonsplass
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: ./models/Produksjonsplass/Produksjonsplass.yaml
        description: ''
      description: Endepunkt for å opprette en produksjonsplass
  /skjemakomponent:
    post:
      summary: Lagrer komponent til angitt eier og skjema
      tags:
        - Skjemakomponent
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/Produksjonsplass/Skjemakomponent/SkjemaKomponent.yaml
        '400':
          description: Bad Request
      operationId: post-skjemakomponent
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/Produksjonsplass/Skjemakomponent/SkjemaKomponent.yaml
        description: Sender inn skjemakomponent som skal lagres
    get:
      summary: Henter alle skjemakomponenter
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/Produksjonsplass/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
      operationId: get-skjemakomponent
  '/skjemakomponent/eier/{eierid}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
    get:
      summary: Henter alle komponenter til angitt eier
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/Produksjonsplass/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid
      description: 'Henter ut alle komponenter som er reigstrert på denne eieren uavhengig av typeskjema, skjemaid'
  '/skjemakomponent/eier/{eierid}/skjema/{skjemaid}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjemaid
        in: path
        required: true
    get:
      summary: Henter alle komponenter til angitt skjema
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/Produksjonsplass/Skjemakomponent/SkjemaKomponent.yaml
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid-skjema-skjemaid
      description: Henter ut alle komponenter som er registrert på angitt eierid og skjemaid
  '/skjemakomponent/eier/{eierid}/skjema/{skjemaid}/komponent/{komponentblokk}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjemaid
        in: path
        required: true
      - schema:
          type: string
        name: komponentblokk
        in: path
        required: true
    get:
      summary: Henter alle komponenter til angitt komponentblokk
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/Produksjonsplass/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk
      description: 'Henter ut alle komponenter som er registrert på angitt eierid,skjemaid og komponentblokk. Komponentblokk er taggen som json strukturen til komponenten ligger under.'
  '/skjemakomponent/eier/{eierid}/skjematype/{skjematype}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjematype
        in: path
        required: true
    get:
      summary: Henter alle komponenter av angitt type
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/Produksjonsplass/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid-skjematype-skjematype
      description: Henter ut alle komponenter som er registrert på angitt eierid og er av angitt skjematype
components:
  schemas:
    PaabegyntSkjema:
      type: object
      x-examples:
        fjorfehold1:
          id: 1
          skjemanavn: fjorfehold
          endretdato: 30.05.2023 13.12
          datajson: '{"dyrehold":[{"id":1,"produksjonsform":"rugeegg"}]}'
          eierId: '09944737728'
        Example 1:
          id: -9223372036854776000
          skjemanavn: string
          endretdato: string
          datajson: string
          eierId: string
      properties:
        id:
          type: integer
          format: int64
        skjemanavn:
          type: string
        endretdato:
          type: string
        datajson:
          type: string
        eierId:
          type: string
          x-stoplight:
            id: d1oyqdhrnoa1d
          description: Ident som er knyttet til eier/bruker.
      description: Skjema som inneholder alle opplysninger i skjema. Eierid er knyttet til den som opprettet skjemaet for å kunne finne riktig skjema. Dette kan være organisasjonsnummer (evnt. virksomhetsmappe i MATS)
      x-tags:
        - Paabegyntskjema
    PaabegyntSkjemaLite:
      title: PaabegyntSkjemaLite
      x-stoplight:
        id: jg99ddm666fdl
      type: object
      description: Påbegynt skjema som bare viser nok informasjon for at brukeren skal kunne velge fra en liste hva hen ønsker fortsette med.
      x-examples:
        Fjorfehold 1:
          id: 1
          dyrehold: fjørfehold
          endretdato: '30.05.2023 10:22'
      properties:
        id:
          type: integer
          x-stoplight:
            id: 9nk8vutid1mtf
          format: int64
          example: 1
        skjemanavn:
          type: string
          x-stoplight:
            id: woqh75nq0mrm9
          example: fjørfehold
        endretdato:
          type: string
          x-stoplight:
            id: kp50ml30jvmoz
          example: '30.05.2023 10:22'
      x-tags:
        - Paabegyntskjema
