openapi: 3.0.0
x-stoplight:
  id: 5rsqq5op2wjt7
info:
  title: produksjonsdyr
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: local
  - url: 'https://stoplight.io/mocks/mattilsynet/produksjonsdyr-api/382663'
    description: mock
paths:
  '/paabegyntskjema/{id}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
        description: identen til påbegynt skjema som skal hentes opp
    get:
      summary: Henter påbegynt skjema
      tags:
        - paabegyntskjema
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaabegyntSkjema'
              examples:
                fjorfehold1:
                  value:
                    id: 1
                    skjemanavn: fjorfehold
                    endretdato: 30.05.2023 13.12
                    datajson: '{"dyrehold":[{"id":1,"produksjonsform":"rugeegg"}]}'
        '404':
          description: Not Found
      operationId: get-paabegyntskjema-id
      description: Henter ut spesifikt påbegynt skjema som har angitt id
  /paabegyntskjema:
    get:
      summary: Henter ut alle påbegynte skjema
      tags:
        - paabegyntskjema
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaabegyntSkjemaLite'
                  x-stoplight:
                    id: 0t5183uosro9f
              examples:
                ReturnererAntall2:
                  value:
                    - id: 1
                      skjemanavn: fjørfehold
                      endretdato: '30.05.2023 10:22'
                    - id: 2
                      skjemanavn: storfehold
                      endretdato: '29.04.2023 11:22'
        '404':
          description: Not Found
      operationId: get-paabegyntskjema
      description: Henter alle påbegynte skjema
    post:
      summary: Lagrer nytt påbegynt skjema
      operationId: post-paabegyntskjema
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaabegyntSkjemaLite'
              examples:
                fjorfehold2:
                  value:
                    id: 2
                    skjemanavn: fjørfehold2
                    endretdato: '31.05.2023 10:22'
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaabegyntSkjema'
            examples:
              NyttSkjema:
                value:
                  skjemanavn: fjorfehold2
                  datajson: '{"dyrehold": [ {"produksjonsform": "slaktekylling" }]  }'
              Example 1:
                value:
                  skjemanavn: string
                  endretdato: string
                  datajson: string
      description: 'Lagrer skjemaet med alle opplysninger som sendes inn. '
  '/paabegyntskjema/byeier/{eierid}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        description: ident som sier hvem brukeren er
        required: true
    get:
      summary: Henter alle skjema til angitt eier
      tags:
        - paabegyntskjema
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaabegyntSkjemaLite'
              examples:
                Example 1:
                  value:
                    - id: 1
                      skjemanavn: fjørfehold
                      endretdato: '30.05.2023 10:22'
                    - id: 2
                      skjemanavn: fjørfehold2
                      endretdato: '01.06.2023 10:22'
        '404':
          description: Not Found
      operationId: get-paabegyntskjema-byeier-eierid
      description: 'Henter ut en liste med skjema som er påbegynt av denne eieren (eierid). '
  '/eier/{eierid}/skjema/{skjemaid}/komponent/':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
        description: eierid til skjema som skal lagres eller utvides
      - schema:
          type: string
        name: skjemaid
        in: path
        required: true
        description: skjemaid til skjema som skal lagres eller utvides
    post:
      summary: Lager ny komponent under angitt skjema
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaabegyntSkjemaLite'
        '400':
          description: Bad Request
      operationId: post-eier-eierid-skjema-skjemaid-komponent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaabegyntSkjema'
            examples:
              Example 1:
                value:
                  skjematype: fjørfehold
                  endretdato: 21.01.2023
                  datajson: '"{\"id\": 1, \"navn\": \"rugeegg\", \"verdikjede\": \"konsumegg\", \"art\": \"hons\", \"kunnskap\": {\"id\": 1, \"tekst\": \"kurs\"}}"'
                  eierId: '23424'
                  komponent: produksjonsform
                  komponentid: 2323
                  skjemaid: '22334'
        description: Body til json strukturen som skal lagres under angitt komponent
    get:
      summary: Henter komponent under angitt skjema
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaabegyntSkjema'
        '404':
          description: Not Found
      operationId: get-eier-eierid-skjema-skjemaid-komponent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas:
    PaabegyntSkjema:
      type: object
      x-examples:
        fjorfehold1:
          id: 1
          skjemanavn: fjorfehold
          endretdato: 30.05.2023 13.12
          datajson: '{"dyrehold":[{"id":1,"produksjonsform":"rugeegg"}]}'
          eierId: '09944737728'
        Example 1:
          id: -9223372036854776000
          skjemanavn: string
          endretdato: string
          datajson: string
          eierId: string
        komponent produksjonsform:
          id: 12121
          skjematype: fjørfehold
          endretdato: 21.06.2023
          datajson: '{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}}'
          eierId: '44433355'
          komponent: produksjonsform
          komponentid: 112
          skjemaid: '945890435893485903'
      description: |-
        Skjema som inneholder alle opplysninger i skjema. Eierid er knyttet til den som opprettet skjemaet for å kunne finne riktig skjema. Dette kan være organisasjonsnummer (evnt. virksomhetsmappe i MATS).
        Dette er et generisk skjema som defineres av json-bolker som ligger under komponent.
      x-tags:
        - paabegyntskjema
      properties:
        id:
          type: integer
          format: int64
          description: Løpetall som idenfifiserer lagret json bolk
        skjematype:
          type: string
          x-stoplight:
            id: rf60exys2htud
          description: 'Dette er navnet på skjema ditt, eller type skjema slik at du kan skille det fra andre skjema du har lagd'
          example: fjørfehold
        endretdato:
          type: string
          example: 21.01.2023
        datajson:
          type: string
          example: '{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}}'
        eierId:
          type: string
          x-stoplight:
            id: d1oyqdhrnoa1d
          description: Ident som er knyttet til eier/bruker.
          example: '23424'
        komponent:
          type: string
          x-stoplight:
            id: hu13htytjhgmw
          description: "Dette er navnet på json-bolken du vil lagre data til.\r\nDette kan være hva som helst."
          example: produksjonsform
        komponentid:
          type: integer
          x-stoplight:
            id: q1dzengxnka7x
          format: int64
          example: 2323
        skjemaid:
          type: string
          x-stoplight:
            id: exuf3wc11pq6b
          description: ident som identifiserer skjemaet som den lagrede json-bolken er knyttet til
          example: '22334'
    PaabegyntSkjemaLite:
      title: PaabegyntSkjemaLite
      x-stoplight:
        id: jg99ddm666fdl
      type: object
      description: Påbegynt skjema som bare viser nok informasjon for at brukeren skal kunne velge fra en liste hva hen ønsker fortsette med.
      x-examples:
        Fjorfehold 1:
          id: 1
          dyrehold: fjørfehold
          endretdato: '30.05.2023 10:22'
          komponent: produksjonsform
      x-tags:
        - paabegyntskjema
      properties:
        id:
          type: integer
          x-stoplight:
            id: 9nk8vutid1mtf
          format: int64
          example: 1
        skjematype:
          type: string
          x-stoplight:
            id: woqh75nq0mrm9
          example: fjørfehold
        endretdato:
          type: string
          x-stoplight:
            id: kp50ml30jvmoz
          example: '30.05.2023 10:22'
        komponent:
          type: string
          x-stoplight:
            id: fp96jm0meoyao
          example: produksjonsform
