title: Produksjonsplass
x-stoplight:
  id: 2kbtfhqicbasr
type: object
description: 'Det offisielle, og eksternt kommuniserte, nivået for anlegg med ID.'
examples:
  - produksjonsplassId: 10000000
    anleggsType: DYREHOLD
    aktiv: true
    fasilitet:
      - aktivitetID: 0
        matsTilsynsobjektID: string
        registreringsDatoAktivitet: '2019-08-24'
        opphørsDatoAktivitet: '2019-08-24'
        kategori:
          kategori: FUGLER
          aktivitetstype:
            aktivitetstypeFugler: RUGEEGG
          verdikjede:
            verdikjedeFugler: KONSUMEGG
        antallTilHensikt:
          artsMengdeID: 0
          fraDato: '2019-08-24'
          mengde:
            - fugleArt: AND
              antall: 5
            - fugleArt: HONS
              antall: 5
        stedsRef:
          - 0
    steder:
      - stedID: 0
        geom: string
        kildeID: string
        kildeURL: no.mattilsynet.mats.virksomhetsmappe.punkt
        hentetTidspunkt: '2019-08-24T14:15:22Z'
        kildeTidspunkt: '2019-08-24T14:15:22Z'
        arkivert: false
    ansvarId:
      - 0
    beskrivelse: string
    visningsNavn: string
x-internal: false
x-tags:
  - Anlegg
properties:
  produksjonsplassId:
    type: integer
    description: 'ID som tildeles alle anlegg i henhold til AHL. skal brukes ved merking av dyr når det brukes "anleggets unike nummer" EU 2016/429, og på transportdokumenter'
    format: int64
    minimum: 10000000
    maximum: 99999999
    x-stoplight:
      id: mc3komkyxjtna
  anleggsType:
    $ref: ../models/ansvarstype.yaml
    description: Ett anlegg kan bare ha en type. Ved behov for flere typer må det opprettes nye anlegg som kan fysisk overlappe andre anlegg
  aktiv:
    type: boolean
    description: 'Forretningsregelen er noe uklar, men vi må kunne representere anlegg som ikke lengre er operative'
    default: true
  fasilitet:
    type: array
    items:
      $ref: ./Fasilitet/Fasilitet.yaml
      x-stoplight:
        id: jmw6d6qvfci39
  steder:
    type: array
    items:
      $ref: ./Sted/Sted.yaml
  ansvarId:
    type: array
    items:
      x-stoplight:
        id: lc5e6zoowcnth
      type: integer
      format: int64
  visningsNavn:
    type: string
    x-stoplight:
      id: re9on7d73pp0h
  risikofaktorer:
    x-stoplight:
      id: jzmhs07xfk31v
    type: array
    items:
      $ref: ./Risikofaktor.yaml
      x-stoplight:
        id: pd2oblcxlv9vj
