title: Produksjonsplass
x-stoplight:
  id: 2kbtfhqicbasr
type: object
description: 'Det offisielle, og eksternt kommuniserte, nivået for anlegg med ID.'
examples:
  - produksjonsplassID: 10000000
    anleggsType: DYREHOLD
    aktiv: true
    aktiviteter:
      - aktivitetID: 0
        matsTilsynsobjektID: string
        registreringsDatoAktivitet: '2019-08-24'
        opphørsDatoAktivitet: '2019-08-24'
        kategori:
          kategori: FUGLER
          aktivitetstype:
            aktivitetstypeFugler: RUGEEGG
          verdikjede:
            verdikjedeFugler: KONSUMEGG
        antallTilHensikt:
          artsMengdeID: 0
          fraDato: '2019-08-24'
          mengde:
            - fugleArt: AND
              antall: 5
            - fugleArt: HONS
              antall: 5
        stedsRef:
          - 0
    steder:
      - stedID: 0
        geom: string
        kildeID: string
        kildeURL: no.mattilsynet.mats.virksomhetsmappe.punkt
        hentetTidspunkt: '2019-08-24T14:15:22Z'
        kildeTidspunkt: '2019-08-24T14:15:22Z'
        arkivert: false
    helsestatus:
      - helsestatusID: 0
        harViDetBra: Det går likar no
        stederRef:
          - 0
        aktiviteterRef:
          - 0
    aktorer:
      - aktorID: 0
        produsentnummerP10: 1234567890
        rolle: Driftsansvarlig
        kanEditereGjeldendeAnlegg: true
        matsPersonId: string
        orgnummerVirksomhet: string
        orgnummerForetak: string
        aktiviteterRef:
          - 0
    anleggMetadata:
      - kapasitet:
          artsMengdeID: 0
          fraDato: '2019-08-24'
          mengde:
            - fugleArt: AND
              antall: 5
            - fugleArt: HONS
              antall: 5
        adresseTekst: string
        adresseIdMatrikkel: string
        beskrivelse: string
        navn: string
x-internal: false
x-tags:
  - Anlegg
properties:
  produksjonsplassId:
    type: integer
    description: 'ID som tildeles alle anlegg i henhold til AHL. skal brukes ved merking av dyr når det brukes "anleggets unike nummer" EU 2016/429, og på transportdokumenter'
    format: int64
    minimum: 10000000
    maximum: 99999999
    x-stoplight:
      id: mc3komkyxjtna
  anleggsType:
    type: string
    enum:
      - DYREHOLD
      - AVLSMATERIALE
      - BIPRODUKTER
      - UTSTILLING
      - FORSØKSDYR
      - SLAKTERI
    description: Ett anlegg kan bare ha en type. Ved behov for flere typer må det opprettes nye anlegg som kan fysisk overlappe andre anlegg
  aktiv:
    type: boolean
    description: 'Forretningsregelen er noe uklar, men vi må kunne representere anlegg som ikke lengre er operative'
    default: true
  fasilitet:
    type: array
    items:
      $ref: ./Fasilitet/Fasilitet.yaml
      x-stoplight:
        id: jmw6d6qvfci39
  steder:
    type: array
    items:
      $ref: ./Sted/Sted.yaml
  ansvarId:
    type: array
    items:
      x-stoplight:
        id: lc5e6zoowcnth
      type: integer
      format: int64
  beskrivelse:
    type: string
    x-stoplight:
      id: gi7nq38lq3s4u
  visningsNavn:
    type: string
    x-stoplight:
      id: re9on7d73pp0h
