title: Produksjonsplass
x-stoplight:
  id: 2kbtfhqicbasr
type: object
description: 'Det offisielle, og eksternt kommuniserte, nivået for anlegg med ID'
x-internal: false
x-tags:
  - Anlegg
properties:
  produksjonsplassID:
    type: integer
    description: 'Sekundær ID som tildeles alle anlegg i henhold til AHL. skal brukes ved merking av dyr når det brukes "anleggets unike nummer" EU 2016/429, og på transportdokumenter'
    format: int64
    minimum: 10000000
    maximum: 99999999
  anleggsType:
    type: string
    enum:
      - DYREHOLD
      - AVLSMATERIALE
      - BIPRODUKTER
      - UTSTILLING
      - FORSØKSDYR
      - SLAKTERI
      - SKYGGE
    description: Ett anlegg kan bare ha en type. Ved behov for flere typer må det opprettes nye anlegg som kan fysisk overlappe andre anlegg
  aktiv:
    type: boolean
    description: 'Forretningsregelen er noe uklar, men vi må kunne representere anlegg som ikke lengre er operative'
    default: true
  aktiviteter:
    type: array
    items:
      $ref: ./Aktivitet/Aktivitet.yaml
  steder:
    type: array
    items:
      $ref: ./Sted/Sted.yaml
  helsestatus:
    type: array
    items:
      $ref: ./Helsestatus/Helsestatus.yaml
  aktorer:
    type: array
    items:
      $ref: ./Aktor/Aktor.yaml
  anleggMetadata:
    type: array
    items:
      $ref: ./AnleggMetadata/AnleggMetadata.yaml
