openapi: 3.0.0
x-stoplight:
  id: o94nyvd1d94mk
info:
  title: Anlegg
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /anlegg:
    post:
      summary: Opprett anlegg
      operationId: post-anlegg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Anlegg.yaml
      x-stoplight:
        id: f5imxrkvk4mht
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Produksjonsplass/AnleggRequest.yaml
            examples: {}
  '/anlegg/{anleggid}/sted':
    parameters:
      - schema:
          type: integer
          format: int64
        name: anleggid
        in: path
        required: true
    post:
      summary: Opprett sted
      operationId: post-anlegg-anleggsid-sted
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/AnleggSted.yaml
      x-stoplight:
        id: 5mqb4g6rpdzfy
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Produksjonsplass/StedRequest.yaml
      description: ''
  '/anlegg/{anleggid}/sted/{stedid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: anleggid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: stedid
        in: path
        required: true
    get:
      summary: ''
      operationId: get-anlegg-anleggid-sted
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Sted.yaml
      x-stoplight:
        id: ex3cp7gnmn81g
  '/anlegg/{anleggid}/sted/{stedid}/fasilitet':
    parameters:
      - schema:
          type: integer
          format: int64
        name: stedid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: anleggid
        in: path
        required: true
    post:
      summary: Opprett fasilitet på et anlegg
      operationId: post-anlegg-(anleggid)-sted-stedid-fasilitet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Fasilitet.yaml
      x-stoplight:
        id: ic58hj9ivxw6q
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Produksjonsplass/FasilitetRequest.yaml
  '/anlegg/{anleggid}/sted/{stedid}/fasilitet/{fasilitetid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: stedid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: anleggid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: fasilitetid
        in: path
        required: true
    get:
      summary: Hent fasilitet
      operationId: get-anlegg-anleggid-sted-stedid-fasilitet-fasilitetid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Fasilitet.yaml
      x-stoplight:
        id: evk0z67nfokir
  '/anlegg/{anleggid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: anleggid
        in: path
        required: true
    get:
      summary: Hent anlegg
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Anlegg.yaml
      operationId: get-anlegg-anleggid
      x-stoplight:
        id: lmdmze0vrlhj1
      description: Henter ut et anlegg gitt ressursid til anlegg
  /anleggForAnsvar:
    post:
      summary: ''
      operationId: post-anleggForAnsvar
      responses:
        '200':
          description: OK
      x-stoplight:
        id: hqfsje45l1wix
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                anleggFasilitetId:
                  type: integer
                  x-stoplight:
                    id: 0wm6rhmm0h2xo
                  format: int64
                ansvarAktivitetId:
                  type: integer
                  x-stoplight:
                    id: pz7rbfny5651m
                  format: int64
      description: Kobler sammen et anlegg med driftsansvar. Dette gjøres på nivået aktivitet og fasilitet fordi en aktivitet knyttes mot dyrerommet aktiviteten foregår i.
components:
  schemas: {}
