openapi: 3.0.0
info:
  title: Anlegg
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /anlegg:
    post:
      summary: Opprett anlegg
      operationId: post-anlegg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Anlegg.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Produksjonsplass/AnleggRequest.yaml
            examples: {}
  '/anlegg/{anleggid}/sted':
    parameters:
      - schema:
          type: integer
          format: int64
        name: anleggid
        in: path
        required: true
    post:
      summary: Opprett sted
      operationId: post-anlegg-anleggsid-sted
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/AnleggSted.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Produksjonsplass/StedRequest.yaml
      description: ''
  '/anlegg/{anleggid}/sted/{stedid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: anleggid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: stedid
        in: path
        required: true
    get:
      summary: ''
      operationId: get-anlegg-anleggid-sted
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Sted.yaml
  '/anlegg/{anleggid}/sted/{stedid}/fasilitet':
    parameters:
      - schema:
          type: integer
          format: int64
        name: stedid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: anleggid
        in: path
        required: true
    post:
      summary: Opprett fasilitet på et anlegg
      operationId: post-anlegg-(anleggid)-sted-stedid-fasilitet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Fasilitet.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Produksjonsplass/FasilitetRequest.yaml
  '/anlegg/{anleggid}/sted/{stedid}/fasilitet/{fasilitetid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: stedid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: anleggid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: fasilitetid
        in: path
        required: true
    get:
      summary: Hent fasilitet
      operationId: get-anlegg-anleggid-sted-stedid-fasilitet-fasilitetid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Fasilitet.yaml
  '/anlegg/{anleggid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: anleggid
        in: path
        required: true
    get:
      summary: Hent anlegg
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Anlegg.yaml
      operationId: get-anlegg-anleggid
      description: Henter ut et anlegg gitt ressursid til anlegg
  /anleggForAnsvar:
    post:
      summary: ''
      operationId: post-anleggForAnsvar
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                anleggFasilitetId:
                  type: integer
                  format: int64
                ansvarAktivitetId:
                  type: integer
                  format: int64
      description: Kobler sammen et anlegg med driftsansvar. Dette gjøres på nivået aktivitet og fasilitet fordi en aktivitet knyttes mot dyrerommet aktiviteten foregår i.
  '/anlegg/tilsynsobjekt/{tilsynsobjektid}':
    parameters:
      - schema:
          type: string
        name: tilsynsobjektid
        in: path
        required: true
        description: referanse til tilsynsobjektet i MATS
    get:
      summary: Hent anlegg for tilsynsobjekt
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Produksjonsplass/Anlegg.yaml
        '404':
          description: Not Found
      operationId: get-anlegg-tilsynsobjektid
      description: 'Henter anlegg som er knyttet til angitt tilsynsobjektid. Dette er en referanse til MATS. '
  '/anlegg/vedlikehold/endrejsonkey/{fraVerdi}/{tilVerdi}':
    parameters:
      - schema:
          type: string
        name: fraVerdi
        in: path
        required: true
        description: fra json key verdi
      - schema:
          type: string
        name: tilVerdi
        in: path
        required: true
        description: til json key verdi
    post:
      summary: Vedlikehold endre json key
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not Found
      operationId: vedlikehol-endrejsonkey-fraVerdi-tilVerdi
      description: 'Dette er en vedlikeholdsoperasjon som skal brukes for å endre jsonkey i anleggstruktur. '
components:
  schemas: {}
