openapi: 3.0.3
info:
  title: AnleggRapportering
  description: Api som brukes for å hente ut lister av anlegg som svarer til angitte kriterier
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  '/rapportering/anleggstatus/{status}/avsluttet/{avsluttet}':
    parameters:
      - schema:
          type: string
        name: status
        in: path
        required: true
      - schema:
          type: boolean
        name: avsluttet
        in: path
        required: false
    get:
      summary: Hent anleggstatus
      operationId: get-anleggstatus
      description: Henter ut alle/ikke avsluttede anlegg som har angitt statuser separart med komma (f.eks. "GODKJENT_EIER,BLANDET")
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: '["anlegg1","anlegg2"]'
  '/rapportering/anleggfasilitet/{egenskap}/verdi/{verdi}/avsluttet/{avsluttet}':
    parameters:
      - schema:
          type: string
        name: egenskap
        in: path
        required: true
      - schema:
          type: string
        name: verdi
        in: path
        required: true
      - schema:
          type: boolean
        name: avsluttet
        in: path
        required: false
    get:
      summary: Hent fasilitet
      operationId: get-fasilitet
      description: Henter ut alle/ikke avsluttede anlegg som har angitt fasilitet med gitt verdi,separart med komma (f.eks. "VERDI1,VERDI2")
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: '["anlegg1","anlegg2"]'
  '/rapportering/anleggfasilitettall/{egenskap}/verdi/{verdi}/operator/{op}/avsluttet/{avsluttet}':
    parameters:
      - schema:
          type: string
        name: egenskap
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: verdi
        in: path
        required: true
      - schema:
          type: string
        name: op
        in: path
        required: true
      - schema:
          type: boolean
        name: avsluttet
        in: path
        required: false
    get:
      summary: Hent anleggfasilitettall
      operationId: get-anleggfasilitettall
      description: Henter ut alle/ikke avsluttede anlegg som har angitt fasilitet med gitt tallverdi ifh operator (f.eks. "kapasitet < 2000")
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: '["anlegg1","anlegg2"]'
  '/rapportering/anleggkontaktpersoner/{egenskap}/verdi/{verdi}/avsluttet/{avsluttet}':
    parameters:
      - schema:
          type: string
        name: egenskap
        in: path
        required: true
      - schema:
          type: string
        name: verdi
        in: path
        required: true
      - schema:
          type: boolean
        name: avsluttet
        in: path
        required: false
    get:
      summary: Hent anleggkontaktpersoner
      operationId: get-anleggkontaktpersoner
      description: Henter ut alle/ikke avsluttede anlegg som har angitt kontaktperson med del av gitt verdi (f.eks. "han", svar kan vær Hansen, Hans Olsen)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: '["anlegg1","anlegg2"]'

