openapi: 3.0.3
info:
  title: AnleggRapportering
  description: Api som brukes for å hente ut lister av anlegg som svarer til angitte kriterier
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  '/rapportering/anleggstatus/{status}/avsluttet/{avsluttet}':
    parameters:
      - schema:
          type: string
        name: status
        in: path
        required: true
      - schema:
          type: boolean
        name: avsluttet
        in: path
        required: false
    get:
      summary: Hent anleggstatus
      operationId: get-anleggstatus
      description: Henter ut alle/ikke avsluttede anlegg som har angitt statuser separart med komma (f.eks. "GODKJENT_EIER,BLANDET")
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: '["anlegg1","anlegg2"]'

