openapi: 3.0.0
info:
  title: ansvar
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /driftsansvar:
    post:
      summary: Opprett driftsansvar
      operationId: post-driftsansvar
      responses:
        '201':
          description: Created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Ansvar/DriftsansvarRequest.yaml
  /driftsansvar/person:
    post:
      summary: Opprett driftsansvarlig for person
      operationId: post-driftansvarligperson
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Driftsansvarlig.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                foedselsnummer:
                  type: string
              required:
                - foedselsnummer
      description: 'Den som har juridisk ansvar for dyr, ofte eieren, men ikke alltid.'
    parameters: []
  /driftsansvar/organisasjon:
    post:
      summary: Opprett driftsansvarlig for foretak
      operationId: post-driftsansvarligorg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Driftsansvarlig.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orgnummerHovedenhet:
                  type: string
              required:
                - orgnummerHovedenhet
      description: 'Den som har juridisk ansvar for dyr, ofte eieren, men ikke alltid.'
    parameters: []
  '/driftsansvar/{driftsansvarid}/kontaktperson':
    post:
      summary: Opprett kontaktperson
      operationId: post-driftsansvarlig-kontaktperson
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Kontaktperson.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Ansvar/KontaktpersonRequest.yaml
            examples:
              Example 1:
                value:
                  fornavn: string
                  etternavn: string
                  telefonnummer: string
                  epost: string
                  roller:
                    - roller: EIER
      description: Oppretter kontaktperson for et gitt driftsansvar. F.eks den som kan konktaktes ved tilsyn
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftsansvarid
        in: path
        required: true
  '/driftsansvar/{driftansvarid}/ansvar':
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftansvarid
        in: path
        required: true
    post:
      summary: Opprett Ansvar
      operationId: post-driftsansvarlig-id-ansvar
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Ansvar.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Ansvar.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Ansvar/AnsvarRequest.yaml
        description: ''
      description: 'I kontekst av dyrehold er ansvar den dyregruppen du har ansvar for. F.eks storfe, eller fjørfe'
  '/driftsansvar/{driftansvarid}/ansvar/{ansvarid}/aktivitet':
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftansvarid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: ansvarid
        in: path
        required: true
    post:
      summary: Opprett aktivitet
      operationId: post-driftsansvarlig-id-ansvar-id-aktivitet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Aktivitet.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Ansvar/AktivitetRequest.yaml
            examples:
              Example 1:
                value:
                  aktivitetstype:
                    aktivitetstypeFugler: RUGEEGG
                    aktivitetstypeStorfe: MELKEKYR
                  verdikjede:
                    verdikjedeFugler: KONSUMEGG
                  art:
                    fugleArt: HONS
                  kunnskap:
                    - kunnskap: UTDANNING
                  antallAarErfaring: -2147483648
                  kunnskapAnnen: string
                  kurs:
                    - kurs: FJOERFEPRODUKSJON
      description: Oppretter aktivitet for et ansvar.
  '/driftsansvar/{driftsansvarid}/ansvar/{ansvarid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftsansvarid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: ansvarid
        in: path
        required: true
    get:
      summary: Hent ut ansvar for en driftsansvarlig
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Ansvar.yaml
      operationId: get-driftsansvar-driftsansvarid-ansvar-ansvarid
  '/driftsansvar/{driftsansvarid}/ansvar/{ansvarid}/aktivitet/{aktivitetid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftsansvarid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: ansvarid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: aktivitetid
        in: path
        required: true
    get:
      summary: GET Aktivitet
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Aktivitet.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Aktivitet.yaml
  '/driftsansvar/tilsynsobjekt/{tilsynsobjektid}':
    parameters:
      - schema:
          type: string
        name: tilsynsobjektid
        in: path
        required: true
        description: tilsynsobjektid i MATS
    get:
      summary: Hent driftsansvarlig for tilsynsobjekt
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Driftsansvarlig.yaml
        '404':
          description: Not Found
      operationId: get-driftsansvar-tilsynsobjektid
      description: Henter ut driftsansvarlig for angitt tilsynsobjekt. Tilsynsobjekt er knytningen mot MATS
components:
  schemas: {}
