openapi: 3.1.0
info:
  title: bbr-stub
  version: '1.0'
  summary: Endepunkt som kun har som ansvar for å stubbe kall mot enhetsregisteret i Brønnøysund
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/enhetsregisteret/api/enheter/{orgnummer}':
    parameters:
      - schema:
          type: string
        name: orgnummer
        in: path
        required: true
    get:
      summary: Enhetsregisteretstub
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enhet'
      operationId: get-enhetsregisteret-api-enheter-orgnummer
      description: Stub for enhetsregisteret i Brønnøysund
components:
  schemas:
    Enhet:
      type: object
      properties:
        organisasjonsnummer:
          type: string
        navn:
          type: string
        organisasjonsform:
          type: object
          properties:
            kode:
              type: string
            beskrivelse:
              type: string
            _links:
              type: object
              properties:
                self:
                  type: object
                  properties:
                    href:
                      type: string
        registreringsdatoEnhetsregisteret:
          type: string
        registrertIMvaregisteret:
          type: boolean
        naeringskode1:
          type: object
          properties:
            beskrivelse:
              type: string
            kode:
              type: string
        antallAnsatte:
          type: integer
        forretningsadresse:
          type: object
          properties:
            land:
              type: string
            landkode:
              type: string
            postnummer:
              type: string
            poststed:
              type: string
            adresse:
              type: array
              items:
                type: string
            kommune:
              type: string
            kommunenummer:
              type: string
        stiftelsesdato:
          type: string
        institusjonellSektorkode:
          type: object
          properties:
            kode:
              type: string
            beskrivelse:
              type: string
        registrertIForetaksregisteret:
          type: boolean
        registrertIStiftelsesregisteret:
          type: boolean
        registrertIFrivillighetsregisteret:
          type: boolean
        sisteInnsendteAarsregnskap:
          type: string
        konkurs:
          type: boolean
        underAvvikling:
          type: boolean
        underTvangsavviklingEllerTvangsopplosning:
          type: boolean
        maalform:
          type: string
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
      x-examples:
        Example 1:
          organisasjonsnummer: '928551725'
          navn: MAWEN AS
          organisasjonsform:
            kode: AS
            beskrivelse: Aksjeselskap
            _links:
              self:
                href: 'https://data.brreg.no/enhetsregisteret/api/organisasjonsformer/AS'
          registreringsdatoEnhetsregisteret: '2022-01-20'
          registrertIMvaregisteret: false
          naeringskode1:
            beskrivelse: Konsulentvirksomhet tilknyttet informasjonsteknologi
            kode: '62.020'
          antallAnsatte: 0
          forretningsadresse:
            land: Norge
            landkode: 'NO'
            postnummer: '2318'
            poststed: HAMAR
            adresse:
              - Holsetgata 62
            kommune: HAMAR
            kommunenummer: '3403'
          stiftelsesdato: '2021-10-25'
          institusjonellSektorkode:
            kode: '2100'
            beskrivelse: Private aksjeselskaper mv.
          registrertIForetaksregisteret: true
          registrertIStiftelsesregisteret: false
          registrertIFrivillighetsregisteret: false
          sisteInnsendteAarsregnskap: '2022'
          konkurs: false
          underAvvikling: false
          underTvangsavviklingEllerTvangsopplosning: false
          maalform: Bokmål
          _links:
            self:
              href: 'https://data.brreg.no/enhetsregisteret/api/enheter/928551725'
      title: Enhet i Brønnøysund
      description: Modell som representerer enhet i Brønnøysund. Brukes kun for stubbing
      examples:
        - organisasjonsnummer: '311929399'
          navn: Kyllingrud AS
          organisasjonsform:
            kode: AS
            beskrivelse: Aksjeselskap
            _links:
              self:
                href: 'https://data.brreg.no/enhetsregisteret/api/organisasjonsformer/AS'
          hjemmeside: www.kyllingrud.no
          registreringsdatoEnhetsregisteret: '2013-04-27'
          registrertIMvaregisteret: true
          naeringskode1:
            beskrivelse: Engroshandel med kjøtt og kjøttvarer
            kode: '46.320'
          antallAnsatte: 1
          forretningsadresse:
            land: Norge
            landkode: 'NO'
            postnummer: '2350'
            poststed: NES PÅ HEDMARKEN
            adresse:
              - Helgøyvegen 960
            kommune: RINGSAKER
            kommunenummer: '3411'
          stiftelsesdato: '2013-04-12'
          institusjonellSektorkode:
            kode: '2100'
            beskrivelse: Private aksjeselskaper mv.
          registrertIForetaksregisteret: true
          registrertIStiftelsesregisteret: false
          registrertIFrivillighetsregisteret: false
          sisteInnsendteAarsregnskap: '2022'
          konkurs: false
          underAvvikling: false
          underTvangsavviklingEllerTvangsopplosning: false
          maalform: Bokmål
          _links:
            self:
              href: 'https://data.brreg.no/enhetsregisteret/api/enheter/311929399'
