openapi: 3.0.0
x-stoplight:
  id: bspqaldw4k34q
info:
  title: BerikelseAPI
  version: '1.0'
  description: 'API som benyttes for å hente informasjon som er nyttig for produksjonsdyr, men som ikke eies av mattilsynet'
servers:
  - url: 'http://localhost:3000'
paths:
  '/berikelse/bygning/masterid/{masterid}':
    get:
      summary: Henter en bygning med gitt masterid
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Sted.yaml
        '404':
          description: Not Found
      operationId: get-bygning
      description: Henter ut bygning med gitt id i master system
    parameters:
      - schema:
          type: string
        name: masterid
        in: path
        required: true
  '/berikelse/bygning/rektangel/{bunnvenstre}/{toppvenstre}/{bunnhoyre}/{topphoyre}/{srid}':
    get:
      summary: Henter bygninger innenfor rektangel
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Produksjonsplass/Sted.yaml
        '404':
          description: Not Found
      operationId: get-bygning-rektangel
      x-stoplight:
        id: suaag2d1kgsft
      description: Henter ut alle bygninger som ligger innenfor angitt rektangel
    parameters:
      - schema:
          type: number
          format: double
        name: bunnvenstre
        in: path
        required: true
      - schema:
          type: number
          format: double
        name: toppvenstre
        in: path
        required: true
      - schema:
          type: number
          format: double
        name: bunnhoyre
        in: path
        required: true
      - schema:
          type: number
          format: double
        name: topphoyre
        in: path
        required: true
      - schema:
          type: integer
          format: int32
        name: srid
        in: path
        required: true
        description: srid/koordinatsystemet som koord er oppgitt i
  '/berikelse/bygning/{nord}/{ost}/{srid}/{radius}':
    parameters:
      - schema:
          type: number
          format: double
        name: nord
        in: path
        required: true
        description: koordinat i nordlig retning
      - schema:
          type: number
          format: double
        name: ost
        in: path
        required: true
        description: koordinat i østlig retning
      - schema:
          type: integer
          format: int32
        name: srid
        in: path
        required: true
        description: koordinatsystem(EPSG) feks 3857
      - schema:
          type: integer
          format: int32
        name: radius
        in: path
        required: true
        description: radius i ant meter som søket leter etter bygninger innenfor
    get:
      summary: Henter bygninger som ligger nært angitt punkt
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Produksjonsplass/Sted.yaml
        '404':
          description: Not Found
      operationId: get-bygg-punkt
      x-stoplight:
        id: h6gn4in0h1zcd
      description: Gjør et geografisk søk etter de nærmeste bygningene
  '/berikelse/teig/{teigid}':
    parameters:
      - schema:
          type: string
        name: teigid
        in: path
        required: true
    get:
      summary: Henter ut teig med gitt id i master system
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Sted.yaml
        '404':
          description: Not Found
      operationId: get-teig
      x-stoplight:
        id: 1h9c8aea8sobm
      description: Henter ut teigen med angitt teigid fra mastersystem
  '/berikelse/teig/rektangel/{bunnvenstre}/{toppvenstre}/{bunnhoyre}/{topphoyre}/{srid}':
    get:
      summary: Henter eiendomsteiger innenfor rektangel
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Produksjonsplass/Sted.yaml
        '404':
          description: Not Found
      operationId: get-teig-rektangel
      x-stoplight:
        id: suaag2d1kgsft
      description: Henter ut alle eiendomsteiger som ligger innenfor angitt rektangel
    parameters:
      - schema:
          type: number
          format: double
        name: bunnvenstre
        in: path
        required: true
      - schema:
          type: number
          format: double
        name: toppvenstre
        in: path
        required: true
      - schema:
          type: number
          format: double
        name: bunnhoyre
        in: path
        required: true
      - schema:
          type: number
          format: double
        name: topphoyre
        in: path
        required: true
      - schema:
          type: integer
          format: int32
        name: srid
        in: path
        required: true
        description: srid/koordinatsystemet som koord er oppgitt i
  '/berikelse/teig/{nord}/{ost}/{srid}/{radius}':
    parameters:
      - schema:
          type: number
          format: double
        name: nord
        in: path
        required: true
        description: koordinat i nordlig retning
      - schema:
          type: number
          format: double
        name: ost
        in: path
        required: true
        description: koordinat i østlig retning
      - schema:
          type: integer
          format: int32
        name: srid
        in: path
        required: true
        description: koordinatsystem(EPSG) feks 3857
      - schema:
          type: integer
          format: int32
        name: radius
        in: path
        required: true
        description: radius i ant meter som søket leter etter eiendommer innenfor
    get:
      summary: Henter eiendommer som ligger nært angitt punkt
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Produksjonsplass/Sted.yaml
        '404':
          description: Not Found
      operationId: get-teig-punkt
      x-stoplight:
        id: hjtftbv2epjmg
      description: 'Gjør et geografisk søk etter de nærmeste eiendommene, dvs deres teiger eller anleggsprojeksjonsflate registrert i matrikkelsystemet.'
  '/berikelse/omrade/rektangel/{bunnvenstre}/{toppvenstre}/{bunnhoyre}/{topphoyre}':
    get:
      summary: Henter geografiske områder innenfor rektangel
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Berikelse/Omrade.yaml
              examples:
                Example 1:
                  value:
                    - id: '152505566'
                      typeomr: no.kartverket.matrikkelen.fkb_bygning
                      geom: 'POLYGON ((1222964.740419269 8562431.953856101, 1223025.209885426 8562416.158561183, 1223022.9931145231 8562407.639415963, 1223020.8214517299 8562399.262018237, 1222960.3521149573 8562415.057239233, 1222962.5237135927 8562423.434673572, 1222964.740419269 8562431.953856101))'
        '404':
          description: Not Found
      operationId: get-omrade-rektangel
      x-stoplight:
        id: 67ivd1ttq78ys
      description: |-
        Henter ut geografiske områder som berører angitt rektangel. Områdene er typisk bygninger eller eiendommer. 
        Områdene er i srid/koordinatsystem EPSG_3857. 
        Metoden er tilpasset frontend.
    parameters:
      - schema:
          type: integer
          format: int64
        name: bunnvenstre
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: toppvenstre
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: bunnhoyre
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: topphoyre
        in: path
        required: true
  '/berikelse/omrade/rektangel/teig/{bunnvenstre}/{toppvenstre}/{bunnhoyre}/{topphoyre}':
    get:
      summary: Henter ut teiger som områder innenfor rektangel
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Berikelse/Omrade.yaml
              examples:
                Example 1:
                  value:
                    - id: '152505566'
                      typeomr: no.kartverket.matrikkelen.fkb_bygning
                      geom: 'POLYGON ((1222964.740419269 8562431.953856101, 1223025.209885426 8562416.158561183, 1223022.9931145231 8562407.639415963, 1223020.8214517299 8562399.262018237, 1222960.3521149573 8562415.057239233, 1222962.5237135927 8562423.434673572, 1222964.740419269 8562431.953856101))'
        '404':
          description: Not Found
      operationId: get-omrade-rektangel-teig
      x-stoplight:
        id: df1rer7v1edf5
      description: Henter ut teiger som berører angitt rektangel. Områdene er eiendommersteiger fra matrikkelen. Områdene er i srid/koordinatsystem EPSG_3857.  Metoden er tilpasset frontend.
    parameters:
      - schema:
          type: integer
          format: int64
        name: bunnvenstre
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: toppvenstre
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: bunnhoyre
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: topphoyre
        in: path
        required: true
  '/berikelse/omrade/rektangel/bygg/{bunnvenstre}/{toppvenstre}/{bunnhoyre}/{topphoyre}':
    get:
      summary: Henter ut bygniger som områder innenfor rektangel
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Berikelse/Omrade.yaml
              examples:
                Example 1:
                  value:
                    - id: '152505566'
                      typeomr: no.kartverket.matrikkelen.fkb_bygning
                      geom: 'POLYGON ((1222964.740419269 8562431.953856101, 1223025.209885426 8562416.158561183, 1223022.9931145231 8562407.639415963, 1223020.8214517299 8562399.262018237, 1222960.3521149573 8562415.057239233, 1222962.5237135927 8562423.434673572, 1222964.740419269 8562431.953856101))'
        '404':
          description: Not Found
      operationId: get-omrade-rektangel-bygg
      x-stoplight:
        id: 8zqkv401c2mjw
      description: Henter ut bygninger som berører angitt rektangel. Områdene er bygniger hentet fra FKB_Bygning.  Områdene er i srid/koordinatsystem EPSG_3857.  Metoden er tilpasset frontend.
    parameters:
      - schema:
          type: integer
          format: int64
        name: bunnvenstre
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: toppvenstre
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: bunnhoyre
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: topphoyre
        in: path
        required: true
  '/berikelse/omrade/punkt/{nord}/{ost}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: nord
        in: path
        required: true
        description: koordinat i nordlig retning
      - schema:
          type: integer
          format: int64
        name: ost
        in: path
        required: true
        description: koordinat i østlig retning
    get:
      summary: Henter geografiske områder som ligger nært angitt punkt
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Berikelse/Omrade.yaml
        '404':
          description: Not Found
      operationId: get-omrade-punkt
      x-stoplight:
        id: hjtftbv2epjmg
      description: |-
        Gjør et geografisk søk etter de nærmeste områdene, dvs bygninger eller teiger registrert i matrikkelsystemet.
        Områdene er i srid/koordinatsystem EPSG_3857. 
        Metoden er tilpasset frontend.
  '/berikelse/omrade/punkt/teig/{nord}/{ost}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: nord
        in: path
        required: true
        description: koordinat i nordlig retning
      - schema:
          type: integer
          format: int64
        name: ost
        in: path
        required: true
        description: koordinat i østlig retning
    get:
      summary: Henter teiger som geografiske områder som ligger nært angitt punkt
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Berikelse/Omrade.yaml
        '404':
          description: Not Found
      operationId: get-omrade-punkt-teig
      x-stoplight:
        id: 2eppj30tz7ogy
      description: Gjør et geografisk søk etter de nærmeste teiger registrert i matrikkelsystemet. Områdene er i srid/koordinatsystem EPSG_3857.  Metoden er tilpasset frontend.
  '/berikelse/omrade/punkt/bygg/{nord}/{ost}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: nord
        in: path
        required: true
        description: koordinat i nordlig retning
      - schema:
          type: integer
          format: int64
        name: ost
        in: path
        required: true
        description: koordinat i østlig retning
    get:
      summary: Henter bygninger som geografiske områder som ligger nært angitt punkt
      tags:
        - berikelse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Berikelse/Omrade.yaml
        '404':
          description: Not Found
      operationId: get-omrade-punkt-bygg
      x-stoplight:
        id: zlgqzx4q1xntt
      description: Gjør et geografisk søk etter de nærmeste bygninger registrert i FKB_Bygning. Områdene er i srid/koordinatsystem EPSG_3857. Metoden er tilpasset frontend.
tags:
  - name: berikelse
