openapi: 3.0.0
x-stoplight:
  id: sqerwwxc1cxui
info:
  title: FrontendSupportAPI
  version: '1.0'
  description: Api som understøtter frontend
servers:
  - url: 'http://localhost:3000'
  - url: 'https://stoplight.io/mocks/mattilsynet/produksjonsdyr-api/382663'
    description: mock
paths:
  /skjemakomponent:
    post:
      summary: Lagrer komponent til angitt eier og skjema
      tags:
        - Skjemakomponent
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
        '400':
          description: Bad Request
      operationId: post-skjemakomponent
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
        description: Sender inn skjemakomponent som skal lagres
    get:
      summary: Henter alle skjemakomponenter
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
      operationId: get-skjemakomponent
  '/skjemakomponent/eier/{eierid}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
    get:
      summary: Henter alle komponenter til angitt eier
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid
      description: 'Henter ut alle komponenter som er reigstrert på denne eieren uavhengig av typeskjema, skjemaid'
    delete:
      summary: ''
      operationId: delete-skjemakomponent-eier-eierid
      responses:
        '200':
          description: OK
  '/skjemakomponent/eier/{eierid}/skjema/{skjemaid}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjemaid
        in: path
        required: true
    get:
      summary: Henter alle komponenter til angitt skjema
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid-skjema-skjemaid
      description: Henter ut alle komponenter som er registrert på angitt eierid og skjemaid
    put:
      summary: ''
      operationId: put-skjemakomponent-eier-eierid-skjema-skjemaid
      responses:
        '200':
          description: OK
    delete:
      summary: ''
      operationId: delete-skjemakomponent-eier-eierid-skjema-skjemaid
      responses:
        '200':
          description: OK
  '/skjemakomponent/eier/{eierid}/skjema/{skjemaid}/komponent/{komponentblokk}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjemaid
        in: path
        required: true
      - schema:
          type: string
        name: komponentblokk
        in: path
        required: true
    get:
      summary: Henter alle komponenter til angitt komponentblokk
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk
      description: 'Henter ut alle komponenter som er registrert på angitt eierid,skjemaid og komponentblokk. Komponentblokk er taggen som json strukturen til komponenten ligger under.'
    put:
      summary: ''
      operationId: put-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk
      responses:
        '200':
          description: OK
    delete:
      summary: ''
      operationId: delete-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk
      responses:
        '200':
          description: OK
  '/skjemakomponent/eier/{eierid}/skjematype/{skjematype}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjematype
        in: path
        required: true
    get:
      summary: Henter alle komponenter av angitt type
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid-skjematype-skjematype
      description: Henter ut alle komponenter som er registrert på angitt eierid og er av angitt skjematype
    put:
      summary: ''
      operationId: put-skjemakomponent-eier-eierid-skjematype-skjematype
      responses:
        '200':
          description: OK
  '/skjemakomponent/eier/{eier}/skjema':
    parameters:
      - schema:
          type: string
        name: eier
        in: path
        required: true
    get:
      summary: Hent alle skjema-metadata for eier
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Skjemakomponent/SkjemaMetadata.yaml
      operationId: get-skjemakomponent-eier-eier-skjema
      description: ''
  '/skjemakomponent/eier/{eierid}/skjema/{skjemaid}/komponent/{komponentblokk}/data':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjemaid
        in: path
        required: true
      - schema:
          type: string
        name: komponentblokk
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk-data
components:
  schemas: {}
