openapi: 3.0.0
x-stoplight:
  id: n49edvl9kto7n
info:
  title: oppsummering
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/innsending/driftsansvar/{driftsansvarid}':
    post:
      summary: Send inn driftsansvar
      operationId: post-innsending
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  driftsansvar:
                    $ref: ../models/Ansvar/Driftsansvarlig.yaml
                  anlegg:
                    $ref: ../models/Produksjonsplass/Anlegg.yaml
      x-stoplight:
        id: lgv8ozvzqyjl8
      description: Endepunkt som bekrefter innsending av driftsansvar og tilhørende anlegg og informasjon. Sender også ut kvittering.
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftsansvarid
        in: path
        required: true
  '/innsending/anlegg/{anleggsid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: anleggsid
        in: path
        required: true
    post:
      summary: Send inn anlegg
      operationId: post-innsending-anlegg-anleggsid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Anlegg.yaml
      x-stoplight:
        id: frte4r9f8sgvl
      description: 'Endepunkt for å bekrefte innsending av anlegg, samt sender ut kvittering.'
  /innsending/ansvarForAnlegg:
    post:
      summary: Send inn ansvarForAnlegg
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  driftsansvar:
                    $ref: ../models/Ansvar/Driftsansvarlig.yaml
                  anlegg:
                    $ref: ../models/Produksjonsplass/Anlegg.yaml
      operationId: post-innsending-ansvarForAnlegg
      x-stoplight:
        id: 5jj6zkv08vpkg
      description: Endepunkt for å bekrefte innsending av ansvar for tilhørende anlegg
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ansvarDriftsansvarId:
                  type: integer
                  x-stoplight:
                    id: 3se30nqptfiwz
                  format: int64
                anleggAnleggsId:
                  type: integer
                  x-stoplight:
                    id: zd682z2polf5m
                  format: int64
  /innsending:
    post:
      summary: Innsending av driftsansvar og anlegg
      operationId: post-innsending-ansvar-anlegg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  driftsansvarId:
                    type: integer
                    x-stoplight:
                      id: mtasesm1ng5li
                    format: int64
                  anleggId:
                    type: integer
                    x-stoplight:
                      id: nugyawfk3anwb
                    format: int64
      x-stoplight:
        id: 7uvkr44wr4d4v
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                driftsansvar:
                  $ref: ../models/Ansvar/DriftsansvarRequest.yaml
                anlegg:
                  $ref: ../models/Produksjonsplass/AnleggRequest.yaml
              required:
                - driftsansvar
                - anlegg
      description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
  /innsending/avsluttdyrehold:
    post:
        summary: Avslutt eksisterende dyrehold
        operationId: post-innsending-avsluttdyrehold
        responses:
          '200':
            description: OK
        requestBody:
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    avsluttetDyrehold:
                      $ref: ../models/Produksjonsplass/AvsluttDyreholdRequest.yaml
                  required:
                    - avsluttetDyrehold
        description: 'Avslutter eksisterende dyrehold. Dyreholdet kan være overført til noen andre'
  /innsending/retryFraLogg:
    post:
      summary: Retry innsending av driftsansvar og anlegg(intern)
      operationId: post-innsending-retry-fra-logg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  driftsansvarId:
                    type: integer
                    format: int64
                  anleggId:
                    type: integer
                    format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                driftsansvar:
                  $ref: ../models/Ansvar/DriftsansvarRequest.yaml
                anlegg:
                  $ref: ../models/Produksjonsplass/AnleggRequest.yaml
              required:
                - driftsansvar
                - anlegg
      description: ''
components:
  schemas: {}
