openapi: 3.0.0
info:
  title: oppsummering
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/innsending/driftsansvar/{driftsansvarid}':
    post:
      summary: Send inn driftsansvar
      operationId: post-innsending
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  driftsansvar:
                    $ref: ../models/Ansvar/Driftsansvarlig.yaml
                  anlegg:
                    $ref: ../models/Produksjonsplass/Anlegg.yaml
      description: Endepunkt som bekrefter innsending av driftsansvar og tilhørende anlegg og informasjon. Sender også ut kvittering.
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftsansvarid
        in: path
        required: true
  '/innsending/anlegg/{anleggsid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: anleggsid
        in: path
        required: true
    post:
      summary: Send inn anlegg
      operationId: post-innsending-anlegg-anleggsid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Anlegg.yaml
      description: 'Endepunkt for å bekrefte innsending av anlegg, samt sender ut kvittering.'
  /innsending/ansvarForAnlegg:
    post:
      summary: Send inn ansvarForAnlegg
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  driftsansvar:
                    $ref: ../models/Ansvar/Driftsansvarlig.yaml
                  anlegg:
                    $ref: ../models/Produksjonsplass/Anlegg.yaml
      operationId: post-innsending-ansvarForAnlegg
      description: Endepunkt for å bekrefte innsending av ansvar for tilhørende anlegg
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ansvarDriftsansvarId:
                  type: integer
                  format: int64
                anleggAnleggsId:
                  type: integer
                  format: int64
  /innsending:
    post:
      summary: Innsending av driftsansvar og anlegg
      operationId: post-innsending-ansvar-anlegg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  driftsansvarId:
                    type: integer
                    format: int64
                  anleggId:
                    type: integer
                    format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                driftsansvar:
                  $ref: ../models/Ansvar/DriftsansvarRequest.yaml
                anlegg:
                  $ref: ../models/Produksjonsplass/AnleggRequest.yaml
              required:
                - driftsansvar
                - anlegg
      description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
  /innsending/oppdateranlegg:
    post:
      summary: Oppdatering av eksisterende driftsansvar og anlegg
      operationId: post-innsending-oppdater-anlegg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  driftsansvarId:
                    type: integer
                    format: int64
                  anleggId:
                    type: integer
                    format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                driftsansvar:
                  $ref: ../models/Ansvar/DriftsansvarRequest.yaml
                anlegg:
                  $ref: ../models/Produksjonsplass/AnleggRequest.yaml
              required:
                - driftsansvar
                - anlegg
      description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
  /innsending/avsluttdyrehold:
    post:
        summary: Avslutt eksisterende dyrehold
        operationId: post-innsending-avsluttdyrehold
        responses:
          '200':
            description: OK
        requestBody:
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    avsluttetDyrehold:
                      $ref: ../models/Produksjonsplass/AvsluttDyreholdRequest.yaml
                  required:
                    - avsluttetDyrehold
        description: 'Avslutter eksisterende dyrehold. Dyreholdet kan være overført til noen andre'
  /innsending/oppdaterfasilitet:
    post:
      summary: Oppdater fasilitet på eksisterende anlegg
      operationId: post-innsending-oppdater-fasilitet
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fasilitet:
                  $ref: ../models/Produksjonsplass/FasilitetRequest.yaml
              required:
                - fasilitet
      description: 'Oppdaterer fasilitet på eksisterende anlegg'
  /innsending/retryFraLogg:
    post:
      summary: Retry innsending av driftsansvar og anlegg(intern)
      operationId: post-innsending-retry-fra-logg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: long
                    format: int64
                  anleggsnummer:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                driftsansvar:
                  $ref: ../models/Ansvar/DriftsansvarRequest.yaml
                anlegg:
                  $ref: ../models/Produksjonsplass/AnleggRequest.yaml
              required:
                - driftsansvar
                - anlegg
      description: ''
  /innsending/anleggmedstatus:
    post:
      summary: Innsending av driftsansvar og anlegg med status
      operationId: post-innsending-ansvar-anlegg-med-status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: long
                    format: int64
                  anleggsnummer:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: ../models/kodeverk/StatusRequest.yaml
                driftsansvar:
                  $ref: ../models/Ansvar/DriftsansvarRequest.yaml
                anlegg:
                  $ref: ../models/Produksjonsplass/AnleggRequest.yaml
              required:
                - driftsansvar
                - anlegg
                - status
      description: 'Innsending fra andre kilder. f.eks analyse eller uttrekk'
components:
  schemas: {}
