openapi: 3.0.0
x-stoplight:
  id: 5rsqq5op2wjt7
info:
  title: Produksjonsplass og Ansvar
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: local
  - url: 'https://stoplight.io/mocks/mattilsynet/produksjonsdyr/382663'
    description: mock
paths:
  '/produksjonsdyr/produksjonsplass/{id}':
    get:
      summary: produksjonsplass
      tags:
        - Produksjonsplass
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Produksjonsplass/Produksjonsplass.yaml
        '404':
          description: Not Found
      operationId: get-produksjonsplass
      x-internal: false
      x-stoplight:
        id: 8cz64lnp6gasp
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
  /produksjonsdyr/produksjonsplass:
    post:
      summary: PostProduksjonsplass
      tags:
        - Produksjonsplass
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: The user ID
        '400':
          description: Bad Request
      operationId: post-produksjonsdyr-produksjonsplass
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Produksjonsplass/Produksjonsplass.yaml
        description: ''
      description: Endepunkt for å opprette en produksjonsplass
      x-stoplight:
        id: tr6zlbr2gq1v4
  '/ansvar/driftsansvarlig/{id}':
    get:
      summary: GetDriftsansvarlig
      tags:
        - Driftsansvarlig
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Driftsansvarlig.yaml
        '404':
          description: Not Found
      operationId: get-produksjonsplass-driftsansvarlig
      x-stoplight:
        id: pomlyr4q0070c
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
  /ansvar/driftsansvarlig:
    post:
      summary: PostDriftsansvarlig
      operationId: post-produksjonsdyr-driftsansvarlig
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: The user ID
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Ansvar/Driftsansvarlig.yaml
      x-stoplight:
        id: yt5wf3fprkwtp
  '/ansvar/driftsansvarlig/{id}/ansvar':
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
    put:
      summary: ''
      operationId: put-ansvar-driftsansvarlig-id-ansvar
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Ansvar/Ansvar.yaml
      description: Legger til et ansvar på en eksisterende driftsansvarlig
      x-stoplight:
        id: ns3bxpui2nx6u
  '/driftsansvarlig/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
                    x-stoplight:
                      id: 5bpjhf8fb5lwq
            application/xml:
              schema:
                $ref: ../models/Ansvar/Driftsansvarlig.yaml
          headers: {}
      operationId: get-driftsansvarlig
      x-stoplight:
        id: sc5ldijav3vjy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      description: ''
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  /privDriftsansvarlig:
    post:
      summary: ''
      operationId: post-privDriftsansvarlig
      responses:
        '200':
          description: OK
      x-stoplight:
        id: 3dhrurri0hs7r
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                foedselsnummer:
                  type: string
                  x-stoplight:
                    id: u2yrbfi8tsnb2
              required:
                - foedselsnummer
          application/xml:
            schema:
              type: object
              properties:
                foedselsnummer:
                  type: string
                  x-stoplight:
                    id: 22y8ey9wv238z
              required:
                - foedselsnummer
        description: ''
  /orgDriftsansvarlig:
    post:
      summary: ''
      operationId: post-orgDriftsansvarlig
      responses:
        '200':
          description: OK
      x-stoplight:
        id: ydfzr6pg6ga26
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                organisasjonsnummerHovedenhet:
                  type: string
                  x-stoplight:
                    id: 7ki71ad4nn5cp
              required:
                - organisasjonsnummerHovedenhet
