openapi: 3.0.3
info:
  title: Vedlikehold
  description: Vedlikehold Api for å kunne endre og oppdatere data i databasen f.eks ifb testing i dev
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  '/vedlikehold/endrejsonkey/{fraVerdi}/{tilVerdi}':
    parameters:
      - schema:
          type: string
        name: fraVerdi
        in: path
        required: true
        description: fra json key verdi
      - schema:
          type: string
        name: tilVerdi
        in: path
        required: true
        description: til json key verdi
    post:
      summary: Vedlikehold endre json key
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not Found
      operationId: endrejsonkey-fraVerdi-tilVerdi
      description: 'Dette er en vedlikeholdsoperasjon som skal brukes for å endre jsonkey i anleggstruktur.'
  '/vedlikehold/settanleggstatus/{anleggnummer}/{status}':
    parameters:
      - schema:
          type: string
        name: anleggnummer
        in: path
        required: true
        description: anleggsnummer som skal endre status
      - schema:
          type: string
        name: status
        in: path
        required: true
        description: status som skal settes for hele anlegget
    post:
      summary: Vedlikehold som setter status for alle modellobjektene under anlegg
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not Found
      operationId: settanleggstatus-anlNummer-status
      description: 'Dette er en vedlikeholdsoperasjon som setter angitt status på hele anlegget.'
  '/vedlikehold/byttOrgFodselUnderOrg/{anleggnummer}/{orgEllerFoedselNr}/{nyOrgEllerFoedselNr}/{orgUnderNr}/{nyOrgUnderNr}':
    parameters:
      - schema:
          type: string
        name: anleggnummer
        in: path
        required: true
        description: anleggsnummer som skal endre orgnummer
      - schema:
          type: string
        name: orgEllerFoedselNr
        in: path
        required: false
        description: org eller fødselsnummer som skal byttes ut
      - schema:
         type: string
        name: nyOrgEllerFoedselNr
        in: path
        required: false
        description: org eller fødselsnummer som skal settes inn
      - schema:
          type: string
        name: orgUnderNr
        in: path
        required: false
        description: undernummer som skal byttes ut
      - schema:
          type: string
        name: nyOrgUnderNr
        in: path
        required: false
        description: org eller fødselsnummer som skal settes inn
    post:
      summary: Vedlikehold som bytter ut angitt org, fødselsnummer eller undernummer med angitt nummer
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not Found
      operationId: byttorgundernummer-anlNummer-org
      description: 'Dette er en vedlikeholdsoperasjon som kan brukes til å bytte ut org, fødselsnummer eller undernummer på et anlegg.'
  '/vedlikehold/anleggmedorgknyttettilflereanlegg/{alle}/antall/{antall}/status/{status}':
    parameters:
      - schema:
          type: boolean
        name: alle
        in: path
        required: true
      - schema:
          type: integer
        name: antall
        in: path
        required: false
      - schema:
          type: string
        name: status
        in: path
        required: false
    get:
      summary: Hent anlegg hvor samme orgnummer er knyttet til flere anlegg
      operationId: get-anleggmedorgknyttettilflereanlegg-alle-antall-status
      description: Henter ut alle eller ønsket antall anlegg som har et orgnummer som er knyttet til flere anlegg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: '["anlegg1","anlegg2"]'
