title: Produksjonsplass
x-stoplight:
  id: 2kbtfhqicbasr
type: object
description: 'Produksjonsplass er et anlegg hvor man kan holde dyr. Produksjonsplass er vårt eget begrep for anlegg, som vi har valgt å bruke fordi det er enklere å ta eierskap til. En produksjonplass er alltid (impliserer) et anlegg. Et anlegg kan være en produksjonsplass, men det kan finnes andre definisjoner av anlegg i regelverk eller dagligtale som ikke er en produksjonsplass. Et anlegg må være registrert i Mattilsynets register for produksjonsplasser for å kvalifisere som en produksjonsplass.'
x-internal: false
x-tags:
  - Anlegg
properties:
  produksjonsplassId:
    type: integer
    description: 'ID som tildeles alle anlegg i henhold til AHL. skal brukes ved merking av dyr når det brukes "anleggets unike nummer" EU 2016/429, og på transportdokumenter'
    format: int64
    minimum: 10000000
    maximum: 99999999
    x-stoplight:
      id: mc3komkyxjtna
  anleggsType:
    $ref: ../kodeverk/Hovedtype.yaml
    description: Ett anlegg kan bare ha en type. Ved behov for flere typer må det opprettes nye anlegg som kan fysisk overlappe andre anlegg
  aktiv:
    type: boolean
    description: 'Forretningsregelen er noe uklar, men vi må kunne representere anlegg som ikke lengre er operative'
    default: true
  steder:
    type: array
    items:
      type: integer
      format: int64
  visningsNavn:
    type: string
    x-stoplight:
      id: re9on7d73pp0h
  risikofaktorer:
    x-stoplight:
      id: jzmhs07xfk31v
    type: array
    items:
      $ref: ./Risikofaktor.yaml
      x-stoplight:
        id: pd2oblcxlv9vj
