name: 'Build'
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
  workflow_dispatch: ~

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build eksport-test-lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        name: Setup Java
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: openApiGenerate
        run: ./gradlew openApiGenerate-task
      - name: Build
        run: ./gradlew build
