name: 'Build'
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
  workflow_dispatch: ~

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build eksport-test-lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: openApiGenerate
        run: sh ./gradlew openApiGenerate-task

      - name: Build
        run: sh ./gradlew build

      - name: Lint YAML
        uses: super-linter/super-linter@v7
        with:
          languages: YAML
          default_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR with yamllint results
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: super-linter.report