name: Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Hva skal vi kalle denne releasen?'
        required: true
        default: "SNAPSHOT"
  release:
    types:
      - created

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 1

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Setup
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: |
          echo Release started
          git remote set-url origin https://oauth2:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git config --global user.email "landdyrdata@mattilsynet.no"
          git config --global user.name "Team Landdyrdata"

      - name: openApiGenerate
        run: ./gradlew openApiGenerate-task

      - name: Publish library
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
        run: |
          echo Release version ${{ github.event.inputs.release_tag }} of produksjonsdyr-api
          ./gradlew publish -PreleaseVersion=${{ github.event.inputs.release_tag }} --info
          
