name: Upgrade Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          target-branch: master
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          pr-title-template: 'gradle: bump gradle wrapper from %sourceVersion% to %targetVersion%'